version: "3.9"
services:
  postgres-compose:
    container_name: postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin123!"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "mydb"
    ports:
      - "0.0.0.0:5432:5432" # Bind to all interfaces on the host
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123!"
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "0.0.0.0:16543:80" # Bind to all interfaces on the host
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

volumes:
  postgres-data:

networks:
  postgres-compose-network:
    driver: bridge